import React,{useEffect,useState} from "react";
import {Routes,Route,Link,useNavigate,useParams} from "react-router-dom";
import axios from "axios";

const API=import.meta.env.VITE_API_URL||"http://localhost:5000";
const api=axios.create({baseURL:API});

function Navbar(){
 const nav=useNavigate(); const user=JSON.parse(localStorage.getItem("matoUser")||"null");
 function logout(){localStorage.removeItem("matoUser");nav("/login");}
 return <nav><Link className="logo" to="/">MATO</Link><div className="links"><Link to="/">Home</Link><Link to="/products">Products</Link>{user&&<><Link to="/cart">Cart</Link><Link to="/wishlist">Wishlist</Link><Link to="/orders">Orders</Link></>}{user?<button onClick={logout}>Logout</button>:<><Link to="/login">Login</Link><Link to="/register">Register</Link></>}</div></nav>
}
function Home(){return <><section className="hero"><div><h1>Fashion for Every Day</h1><p>Discover new styles at great prices.</p><Link className="btn" to="/products">Shop Now</Link></div></section><h2>Shop by Category</h2><div className="cats">{["Men","Women","Footwear","Accessories"].map(x=><Link key={x} to={"/products?category="+x}>{x}</Link>)}</div></>}
function Products(){const [ps,setPs]=useState([]),[search,setSearch]=useState(""),[sort,setSort]=useState(""); const [cat,setCat]=useState("All");
 async function load(){const r=await api.get("/products",{params:{search,sort,category:cat}});setPs(r.data)} useEffect(()=>{load()},[sort,cat]);
 return <><div className="toolbar"><input placeholder="Search products..." value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><select value={cat} onChange={e=>setCat(e.target.value)}><option>All</option><option>Men</option><option>Women</option><option>Footwear</option><option>Accessories</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="">Sort</option><option value="low">Price Low-High</option><option value="high">Price High-Low</option><option value="new">Newest</option></select></div><div className="grid">{ps.map(p=><ProductCard key={p._id} p={p}/>)}</div></>}
function ProductCard({p}){return <Link className="card" to={"/products/"+p._id}><img src={p.image}/><h3>{p.name}</h3><p>{p.brand}</p><b>₹{p.price}</b> <span className="discount">{p.discount}% OFF</span></Link>}
function ProductDetails(){const {id}=useParams(),[p,setP]=useState(null),[size,setSize]=useState(""),[msg,setMsg]=useState(""); const user=JSON.parse(localStorage.getItem("matoUser")||"null");
 useEffect(()=>{api.get("/products/"+id).then(r=>setP(r.data))},[id]); if(!p)return <p>Loading...</p>;
 async function add(){if(!user)return alert("Please login first");await api.post("/cart",{userId:user.id,productId:p._id,quantity:1,size:size||p.sizes[0],color:p.colors[0]});setMsg("Added to cart");}
 async function wish(){if(!user)return alert("Please login first");await api.post("/wishlist",{userId:user.id,productId:p._id});setMsg("Added to wishlist");}
 return <div className="details"><img src={p.image}/><div><h1>{p.name}</h1><p>{p.description}</p><h2>₹{p.price}</h2><p>Rating ⭐ {p.rating}</p><label>Size <select value={size} onChange={e=>setSize(e.target.value)}>{p.sizes.map(s=><option key={s}>{s}</option>)}</select></label><div><button className="btn" onClick={add}>Add to Cart</button><button onClick={wish}>Wishlist</button></div><p>{msg}</p></div></div>}
function Login(){const nav=useNavigate();const [f,setF]=useState({email:"",password:""}),[err,setErr]=useState("");async function submit(e){e.preventDefault();try{const r=await api.post("/login",f);localStorage.setItem("matoUser",JSON.stringify(r.data.user));nav("/")}catch(e){setErr(e.response?.data?.message||"Login failed")}}return <Form title="Login" fields={f} setFields={setF} submit={submit} err={err} button="Login"/>}
function Register(){const nav=useNavigate();const [f,setF]=useState({name:"",email:"",password:""}),[err,setErr]=useState("");async function submit(e){e.preventDefault();try{await api.post("/register",f);nav("/login")}catch(e){setErr(e.response?.data?.message||"Registration failed")}}return <Form title="Create Account" fields={f} setFields={setF} submit={submit} err={err} button="Register"/>}
function Form({title,fields,setFields,submit,err,button}){return <form className="form" onSubmit={submit}><h2>{title}</h2>{Object.keys(fields).map(k=><input key={k} type={k==="password"?"password":"text"} placeholder={k[0].toUpperCase()+k.slice(1)} value={fields[k]} onChange={e=>setFields({...fields,[k]:e.target.value})} required/>)}<button className="btn">{button}</button><p className="error">{err}</p></form>}
function Cart(){const user=JSON.parse(localStorage.getItem("matoUser")||"null"),[items,setItems]=useState([]);const nav=useNavigate();useEffect(()=>{if(user)api.get("/cart/"+user.id).then(r=>setItems(r.data))},[]);if(!user)return <NavigateLogin/>;const total=items.reduce((a,x)=>a+x.product.price*x.quantity,0);async function remove(id){await api.delete("/cart/"+id);setItems(items.filter(x=>x._id!==id))}return <><h2>Your Cart</h2>{items.map(x=><div className="row" key={x._id}><img src={x.product.image}/><div><h3>{x.product.name}</h3><p>₹{x.product.price} × {x.quantity}</p><button onClick={()=>remove(x._id)}>Remove</button></div></div>)}<h2>Total: ₹{total}</h2>{items.length>0&&<button className="btn" onClick={()=>nav("/checkout")}>Checkout</button>}</>}
function Wishlist(){const user=JSON.parse(localStorage.getItem("matoUser")||"null"),[items,setItems]=useState([]);useEffect(()=>{if(user)api.get("/wishlist/"+user.id).then(r=>setItems(r.data))},[]);if(!user)return <NavigateLogin/>;return <><h2>Wishlist</h2><div className="grid">{items.map(x=><ProductCard key={x._id} p={x.product}/>)}</div></>}
function Checkout(){const user=JSON.parse(localStorage.getItem("matoUser")||"null"),[form,setForm]=useState({name:"",phone:"",address:"",city:"",pincode:""});const nav=useNavigate();if(!user)return <NavigateLogin/>;async function place(e){e.preventDefault();const c=await api.get("/cart/"+user.id);const total=c.data.reduce((a,x)=>a+x.product.price*x.quantity,0);await api.post("/orders",{userId:user.id,items:c.data.map(x=>({productId:x.product._id,name:x.product.name,quantity:x.quantity,price:x.product.price})),total,address:form});for(const x of c.data)await api.delete("/cart/"+x._id);nav("/orders")}return <form className="form" onSubmit={place}><h2>Checkout</h2>{Object.keys(form).map(k=><input key={k} placeholder={k} value={form[k]} required onChange={e=>setForm({...form,[k]:e.target.value})}/>) }<button className="btn">Place Order</button></form>}
function Orders(){const user=JSON.parse(localStorage.getItem("matoUser")||"null"),[os,setOs]=useState([]);useEffect(()=>{if(user)api.get("/orders/"+user.id).then(r=>setOs(r.data))},[]);if(!user)return <NavigateLogin/>;return <><h2>My Orders</h2>{os.map(o=><div className="order" key={o._id}><b>Order #{o._id.slice(-6)}</b><p>Total: ₹{o.total}</p><p>Status: {o.status}</p><small>{new Date(o.createdAt).toLocaleString()}</small></div>)}</>}
function NavigateLogin(){const nav=useNavigate();useEffect(()=>nav("/login"),[]);return null}
function Admin(){const [ps,setPs]=useState([]),[form,setForm]=useState({name:"",category:"Men",brand:"Mato",price:"",discount:0,image:"",description:""});async function load(){setPs((await api.get("/products")).data)}useEffect(()=>{load()},[]);async function add(e){e.preventDefault();await api.post("/products",{...form,price:Number(form.price),sizes:["S","M","L","XL"],colors:["Black","White"]});setForm({...form,name:"",price:""});load()}async function del(id){await api.delete("/products/"+id);load()}return <><h2>Admin - Product Management</h2><form className="adminform" onSubmit={add}>{["name","brand","price","image","description"].map(k=><input key={k} placeholder={k} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} required/>)}<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Men</option><option>Women</option><option>Footwear</option><option>Accessories</option></select><button className="btn">Add Product</button></form><div className="grid">{ps.map(p=><div className="card" key={p._id}><img src={p.image}/><h3>{p.name}</h3><button onClick={()=>del(p._id)}>Delete</button></div>)}</div></>}
export default function App(){return <><Navbar/><main><Routes><Route path="/" element={<Home/>}/><Route path="/products" element={<Products/>}/><Route path="/products/:id" element={<ProductDetails/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/cart" element={<Cart/>}/><Route path="/wishlist" element={<Wishlist/>}/><Route path="/checkout" element={<Checkout/>}/><Route path="/orders" element={<Orders/>}/><Route path="/admin" element={<Admin/>}/></Routes></main><footer>Mato Clone • College MERN Project</footer></>}
